### ISSUE TITLE
页面没有渲染(partial转义失败)

### ISSUE THREAD

**Issue by SunHuaiju** [mtics/hexo-mtics-resume#2]
请问部署以后页面不渲染，发生partial转义失败。执行
```
npm install
```
或者换用xshell终端，都无法解决。
请问还有什么解决办法吗

**Comment by mtics** [comment]
不好意思，因我最近开学太忙，所以没时间处理这个了。

整个项目并没有用到额外的插件，如果出现了插件错误，应该是您配置出现了问题。

**Comment by HonFii** [comment]
我也是这个问题，可能是某一部分版本出现问题，目前没解决

**Comment by mtics** [comment]
> 我也是这个问题，可能是某一部分版本出现问题，目前没解决

你们试着使用一下"develop"分支中的代码试试，这个版本我更新过一些代码，说不定会能用。因为我本地新建项目都是没问题的，所以不知道怎么复现你们的错误

**Comment by w158rk** [comment]
试一下： npm install hexo-renderer-swig

**Comment by SunHuaiju** [comment]
> 试一下： npm install hexo-renderer-swig
使用这个命令以后，问题就解决了。。

**Comment by mtics** [comment]
> 试一下： npm install hexo-renderer-swig

thx, it really helps!

**Comment by PearlLiu-Dev** [comment]
现在要用这个：npm install hexo-renderer-nunjucks（问题已解决）
